[build]
  publish = "public"
  command = "npm run build"
[context.branch-deploy]
  ignore = '''
  if echo $BRANCH | grep "^feature" ;
    return 1
  else
    return 0
  fi
  '''
[build.environment]
  NODE_VERSION = "12"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"