[build]
  publish = "public"
  command = "npm run build"
[context.branch-deploy]
  ignore = "bash ./netlify-build-ignore.sh"
[build.environment]
  NODE_VERSION = "12"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
     Referrer-Policy = "strict-origin-when-cross-origin"
[[redirects]]
from = "https://starsfest2022.com/*" 
to = "https://starsfest2022.fnvirtual.app/:splat"
status = 301
force = true
[[redirects]]
from = "https://www.starsfest2022.com/*"
to = "https://starsfest2022.fnvirtual.app/:splat"
status = 301
force = true
[[redirects]]
from = "/competition"
to = "/creator-competition"
status = 301
force = true
