[build]
  publish = "public"
  command = "npm run build"
[context.branch-deploy]
  ignore = "bash ./netlify-build-ignore.sh"
[build.environment]
  NODE_VERSION = "12"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
     Referrer-Policy = "strict-origin-when-cross-origin"
[[redirects]]
https://starfest2022.com/* https://starfest2022.fnvirtual.app:splat 301!
https://www.starfest2022.com/* https://starfest2022.fnvirtual.app:splat 301!
