backend:
  name: github
  branch: master
  repo: fntechgit/virtualevent-poc
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "configurations"
    label: "Configurations"
    editor:
      preview: false
    files:
      - file: "src/content/ads.json"
        label: "Sponsor Ads"
        name: "ads"
        fields:
          - {label: "Sponsor Ads", name: "ads", widget: list, fields: [
              {label: "Section", name: "section", widget: string},
              {label: "Columns", name: "columns", widget: list, fields: [
                {label: "Column", name: "column", widget: select, options: [
                  { label: "Left", value: "left" },
                  { label: "Center", value: "center" },
                  { label: "Right", value: "right" },
                ]},               
                {label: "Ads", name: "ads", widget: list, required: false, fields: [
                  {label: "Image", name: "image", widget: image},
                  {label: "Text", name: "text", widget: string},
                  {label: "Button", name: button, widget: object, fields: [
                    {label: "Text", name: "text", widget: string},
                    {label: "Link", name: "link", widget: string}
                  ]},
                  {label: "Specific Event?", name: "id", widget: string, required: false}
                ]}
              ]},              
            ]}