name: Sync Base Branches
on:
  push:
    branches:
      - 'main'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge main -> dev-yoco
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: main
          target_branch: dev-yoco
          github_token: ${{ github.token }}

#      - name: Merge dev-yoco -> prod-yoco
#        uses: devmasx/merge-branch@v1.3.1
#        with:
#          type: now
#          from_branch: dev-yoco
#          target_branch: prod-yoco
#          github_token: ${{ github.token }}
#
#      - name: Merge main -> prod-tier1
#        uses: devmasx/merge-branch@v1.3.1
#        with:
#          type: now
#          from_branch: main
#          target_branch: prod-tier_1_default
#          github_token: ${{ github.token }}

      - name: The job has failed
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: message,author,job
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ failure() }}